ALTER TABLE gw_product_function ADD COLUMN IF NOT EXISTS payload_encoding VARCHAR(16) NOT NULL DEFAULT 'JSON';
ALTER TABLE gw_write_option ADD COLUMN IF NOT EXISTS byte_length INTEGER NULL;
ALTER TABLE gw_write_option ADD COLUMN IF NOT EXISTS byte_order VARCHAR(16) NULL;
ALTER TABLE gw_read_field ADD COLUMN IF NOT EXISTS byte_length INTEGER NULL;
ALTER TABLE gw_read_field ADD COLUMN IF NOT EXISTS byte_order VARCHAR(16) NULL;
